defaults: &default
    resource_class: small
    gcr_auth:
        description: Auth GCR
        steps:
          - setup_remote_docker
          - run:
              name: GCR auth
              command: echo $GCLOUD_GCR_BUILDER | docker login -u _json_key --password-stdin https://gcr.io/snyk-main
    docker:
        auth:
            username: _json_key
            password: $GCLOUD_GCR_BUILDER
version: 2
jobs:
    build:
        working_directory: ~/pubsubbeat
        docker:
            - image: docker:18.02.0-ce
        steps:
            - checkout
            - gcr_auth #remove, for debugging
            - setup_remote_docker:
                docker_layer_caching: true
            - run: docker build -t gcr.io/snyk-main/pubsubbeat:${CIRCLE_SHA1} .
            - run: 
                name: docker save gcr.io/snyk-main/pubsubbeat:${CIRCLE_SHA1} 
                command: mkdir -p ~/pubsubbeat/cache; docker save -o ~/pubsubbeat/cache/docker.tar "gcr.io/snyk-main/pubsubbeat:${CIRCLE_SHA1}"
            - save_cache:
                key: v1-{{ .Branch }}-{{ .Environment.CIRCLE_TAG }}-{{ epoch }}
                paths:
                    - ~/pubsubbeat/cache/docker.tar
            - attach_workspace:
                at: ~/pubsubbeat
    push:
        docker:
            - image: docker:18.02.0-ce
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - restore_cache:
                key: v1-{{.Branch}}
            - run:
                name: Restore Docker image cache
                command: docker load -i ~/pubsubbeat/cache/docker.tar
            - gcr_auth
            - run: 
                name: push to gcr.io
                command: docker push gcr.io/snyk-main/pubsubbeat:${CIRCLE_SHA1}
workflows:
    version: 2
    build_and_push:
        jobs:
            - build
            - push:
                context: snyk-docker-build
                requires:
                    - build
