defaults: &default
    resource_class: small
    docker:
        auth:
            username: _json_key
            password: $GCLOUD_GCR_BUILDER
version: 2
jobs:
    build:
        working_directory: ~/pubsubbeat
        machine: true
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run: |
                docker build -t gcr.io/snyk-main/pubsubbeat:${CIRCLE_SHA1} .
            - attach_workspace:
                at: ~/pubsubbeat
    push:
        machine: true
        steps:
            - attach_workspace:
                at: ~/pubsubbeat
            - run: docker push gcr.io/snyk-main/pubsubbeat:${CIRCLE_SHA1}
workflows:
    version: 2
    build_and_push:
        jobs:
            - build
            - push:
                context: snyk-docker-build
                requires:
                    - build
